const seedPalettes = [
  {
    paletteName: "Material UI Colors",
    id: "material-ui-colors",
    colors: [
      { name: "red", value: "#F44336" },
      { name: "pink", value: "#E91E63" },
      { name: "purple", value: "#9C27B0" },
      { name: "deeppurple", value: "#673AB7" },
      { name: "indigo", value: "#3F51B5" },
      { name: "blue", value: "#2196F3" },
      { name: "lightblue", value: "#03A9F4" },
      { name: "cyan", value: "#00BCD4" },
      { name: "teal", value: "#009688" },
      { name: "green", value: "#4CAF50" },
      { name: "lightgreen", value: "#8BC34A" },
      { name: "lime", value: "#CDDC39" },
      { name: "yellow", value: "#FFEB3B" },
      { name: "amber", value: "#FFC107" },
      { name: "orange", value: "#FF9800" },
      { name: "deeporange", value: "#FF5722" },
      { name: "brown", value: "#795548" },
      { name: "grey", value: "#9E9E9E" },
      { name: "bluegrey", value: "#607D8B" }
    ]
  },
  {
    paletteName: "Flat UI Colors v1",
    id: "flat-ui-colors-v1",
    colors: [
      { name: "Turquoise", value: "#1abc9c" },
      { name: "Emerald", value: "#2ecc71" },
      { name: "PeterRiver", value: "#3498db" },
      { name: "Amethyst", value: "#9b59b6" },
      { name: "WetAsphalt", value: "#34495e" },
      { name: "GreenSea", value: "#16a085" },
      { name: "Nephritis", value: "#27ae60" },
      { name: "BelizeHole", value: "#2980b9" },
      { name: "Wisteria", value: "#8e44ad" },
      { name: "MidnightBlue", value: "#2c3e50" },
      { name: "SunFlower", value: "#f1c40f" },
      { name: "Carrot", value: "#e67e22" },
      { name: "Alizarin", value: "#e74c3c" },
      { name: "Clouds", value: "#ecf0f1" },
      { name: "Concrete", value: "#95a5a6" },
      { name: "Orange", value: "#f39c12" },
      { name: "Pumpkin", value: "#d35400" },
      { name: "Pomegranate", value: "#c0392b" },
      { name: "Silver", value: "#bdc3c7" },
      { name: "Asbestos", value: "#7f8c8d" }
    ]
  },
  {
    paletteName: "Flat UI Colors Dutch",
    id: "flat-ui-colors-dutch",
    colors: [
      { name: "Sunflower", value: "#FFC312" },
      { name: "Energos", value: "#C4E538" },
      { name: "BlueMartina", value: "#12CBC4" },
      { name: "LavenderRose", value: "#FDA7DF" },
      { name: "BaraRose", value: "#ED4C67" },
      { name: "RadiantYellow", value: "#F79F1F" },
      { name: "AndroidGreen", value: "#A3CB38" },
      { name: "MediterraneanSea", value: "#1289A7" },
      { name: "LavenderTea", value: "#D980FA" },
      { name: "VerryBerry", value: "#B53471" },
      { name: "PuffinsBill", value: "#EE5A24" },
      { name: "PixelatedGrass", value: "#009432" },
      { name: "MerchantMarineBlue", value: "#0652DD" },
      { name: "ForgottenPurple", value: "#9980FA" },
      { name: "HollyHock", value: "#833471" },
      { name: "RedPigment", value: "#EA2027" },
      { name: "TurkishAqua", value: "#006266" },
      { name: "20000LeaguesUnderTheSea", value: "#1B1464" },
      { name: "CircumorbitalRing", value: "#5758BB" },
      { name: "MagentaPurple", value: "#6F1E51" }
    ]
  },
  {
    paletteName: "Flat UI Colors American",
    id: "flat-ui-colors-american",
    colors: [
      { name: "LightGreenishBlue", value: "#55efc4" },
      { name: "FadedPoster", value: "#81ecec" },
      { name: "GreenDarnerTail", value: "#74b9ff" },
      { name: "ShyMoment", value: "#a29bfe" },
      { name: "CityLights", value: "#dfe6e9" },
      { name: "MintLeaf", value: "#00b894" },
      { name: "RobinsEggBlue", value: "#00cec9" },
      { name: "ElectronBlue", value: "#0984e3" },
      { name: "ExodusFruit", value: "#6c5ce7" },
      { name: "SoothingBreeze", value: "#b2bec3" },
      { name: "SourLemon", value: "#ffeaa7" },
      { name: "FirstDate", value: "#fab1a0" },
      { name: "PinkGlamour", value: "#ff7675" },
      { name: "Pico8Pink", value: "#fd79a8" },
      { name: "AmericanRiver", value: "#636e72" },
      { name: "BrightYarrow", value: "#fdcb6e" },
      { name: "OrangeVille", value: "#e17055" },
      { name: "Chi-Gong", value: "#d63031" },
      { name: "PrunusAvium", value: "#e84393" },
      { name: "DraculaOrchid", value: "#2d3436" }
    ]
  },
  {
    paletteName: "Flat UI Colors Aussie",
    id: "flat-ui-colors-aussie",
    colors: [
      { name: "Beekeeper", value: "#f6e58d" },
      { name: "SpicedNectarine", value: "#ffbe76" },
      { name: "PinkGlamour", value: "#ff7979" },
      { name: "JuneBud", value: "#badc58" },
      { name: "CoastalBreeze", value: "#dff9fb" },
      { name: "Turbo", value: "#f9ca24" },
      { name: "QuinceJelly", value: "#f0932b" },
      { name: "CarminePink", value: "#eb4d4b" },
      { name: "PureApple", value: "#6ab04c" },
      { name: "HintOfIcePack", value: "#c7ecee" },
      { name: "MiddleBlue", value: "#7ed6df" },
      { name: "Heliotrope", value: "#e056fd" },
      { name: "ExodusFruit", value: "#686de0" },
      { name: "DeepKoamaru", value: "#30336b" },
      { name: "SoaringEagle", value: "#95afc0" },
      { name: "GreenlandGreen", value: "#22a6b3" },
      { name: "SteelPink", value: "#be2edd" },
      { name: "Blurple", value: "#4834d4" },
      { name: "DeepCove", value: "#130f40" },
      { name: "WizardGrey", value: "#535c68" }
    ]
  },
  {
    paletteName: "Flat UI Colors British",
    id: "flat-ui-colors-british",
    colors: [
      { name: "ProtossPylon", value: "#00a8ff" },
      { name: "Periwinkle", value: "#9c88ff" },
      { name: "Rise-N-Shine", value: "#fbc531" },
      { name: "DownloadProgress", value: "#4cd137" },
      { name: "Seabrook", value: "#487eb0" },
      { name: "VanaDylBlue", value: "#0097e6" },
      { name: "MattPurple", value: "#8c7ae6" },
      { name: "NanohanachaGold", value: "#e1b12c" },
      { name: "SkirretGreen", value: "#44bd32" },
      { name: "Naval", value: "#40739e" },
      { name: "NasturcianFlower", value: "#e84118" },
      { name: "LynxWhite", value: "#f5f6fa" },
      { name: "BlueberrySoda", value: "#7f8fa6" },
      { name: "MazarineBlue", value: "#273c75" },
      { name: "BlueNights", value: "#353b48" },
      { name: "HarleyOrange", value: "#c23616" },
      { name: "HintOfPensive", value: "#dcdde1" },
      { name: "ChainGangGrey", value: "#718093" },
      { name: "PicoVoid", value: "#192a56" },
      { name: "ElectroMagnetic", value: "#2f3640" }
    ]
  },
  {
    paletteName: "Flat UI Colors Spanish",
    id: "flat-ui-colors-spanish",
    colors: [
      { name: "JacksonsPurple", value: "#40407a" },
      { name: "C64Purple", value: "#706fd3" },
      { name: "SwanWhite", value: "#f7f1e3" },
      { name: "SummerSky", value: "#34ace0" },
      { name: "CelestialGreen", value: "#33d9b2" },
      { name: "LuckyPoint", value: "#2c2c54" },
      { name: "Liberty", value: "#474787" },
      { name: "HotStone", value: "#aaa69d" },
      { name: "DevilBlue", value: "#227093" },
      { name: "PalmSpringsSplash", value: "#218c74" },
      { name: "FlourescentRed", value: "#ff5252" },
      { name: "SyntheticPumpkin", value: "#ff793f" },
      { name: "CrocodileTooth", value: "#d1ccc0" },
      { name: "MandarinSorbet", value: "#ffb142" },
      { name: "SpicedButterNut", value: "#ffda79" },
      { name: "EyeOfNewt", value: "#b33939" },
      { name: "ChileanFire", value: "#cd6133" },
      { name: "GreyPorcelain", value: "#84817a" },
      { name: "AlamedaOchre", value: "#cc8e35" },
      { name: "Desert", value: "#ccae62" }
    ]
  },
  {
    paletteName: "Flat UI Colors Indian",
    id: "flat-ui-colors-indian",
    colors: [
      { name: "OrchidOrange", value: "#FEA47F" },
      { name: "SpiroDiscoBall", value: "#25CCF7" },
      { name: "HoneyGlow", value: "#EAB543" },
      { name: "SweetGarden", value: "#55E6C1" },
      { name: "FallingStar", value: "#CAD3C8" },
      { name: "RichGardenia", value: "#F97F51" },
      { name: "ClearChill", value: "#1B9CFC" },
      { name: "WhitePepper", value: "#F8EFBA" },
      { name: "Keppel", value: "#58B19F" },
      { name: "ShipsOfficer", value: "#2C3A47" },
      { name: "FieryFuchsia", value: "#B33771" },
      { name: "BlueBell", value: "#3B3B98" },
      { name: "GeorgiaPeach", value: "#FD7272" },
      { name: "OasisStream", value: "#9AECDB" },
      { name: "BrightUbe", value: "#D6A2E8" },
      { name: "MagentaPurple", value: "#6D214F" },
      { name: "EndingNavyBlue", value: "#182C61" },
      { name: "SasquatchSocks", value: "#FC427B" },
      { name: "PineGlade", value: "#BDC581" },
      { name: "HighlighterLavender", value: "#82589F" }
    ]
  },
  {
    paletteName: "Flat UI Colors French",
    id: "flat-ui-colors-french",

    colors: [
      { name: "FlatFlesh", value: "#fad390" },
      { name: "MelonMelody", value: "#f8c291" },
      { name: "Livid", value: "#6a89cc" },
      { name: "Spray", value: "#82ccdd" },
      { name: "ParadiseGreen", value: "#b8e994" },
      { name: "SquashBlossom", value: "#f6b93b" },
      { name: "MandarinRed", value: "#e55039" },
      { name: "AzraqBlue", value: "#4a69bd" },
      { name: "Dupain", value: "#60a3bc" },
      { name: "AuroraGreen", value: "#78e08f" },
      { name: "IcelandPoppy", value: "#fa983a" },
      { name: "TomatoRed", value: "#eb2f06" },
      { name: "YueGuangBlue", value: "#1e3799" },
      { name: "GoodSamaritan", value: "#3c6382" },
      { name: "Waterfall", value: "#38ada9" },
      { name: "CarrotOrange", value: "#e58e26" },
      { name: "JalapenoRed", value: "#b71540" },
      { name: "DarkSapphire", value: "#0c2461" },
      { name: "ForestBlues", value: "#0a3d62" },
      { name: "ReefEncounter", value: "#079992" }
    ]
  }
];

export default seedPalettes;